[project]
version = "0.0.1"
description="PyTrapIC - Python Transpiler to IC10 for Stationeers"
license = "MIT"
name = "stationeers_pytrapic"
dependencies = ['astroid']
requires-python = ">=3.10"

[build-system]
requires = ["setuptools>=60", "wheel"]
build-backend = "setuptools.build_meta"
